import Link from "next/link";
import { Article, articlePath, articles } from "@/lib/content";
import { estimateReadingMinutes, getArticleReferences, getResearchProfile } from "@/lib/article-enrichment";
import { ArticleProgress, BookmarkButton, ReadingControls } from "./article-tools";

function AnchorHeading({id,children}:{id:string;children:React.ReactNode}){return <h2 id={id}>{children} <a href={`#${id}`} aria-label={`Link to ${String(children)}`}>#</a></h2>}

export default function ArticlePage({article}:{article:Article}){
  const related=articles.filter(a=>a.slug!==article.slug&&(a.category===article.category||a.tags.some(t=>article.tags.includes(t)))).slice(0,3);
  const profile=getResearchProfile(article);
  const refs=getArticleReferences(article);
  const minutes=estimateReadingMinutes(article);
  const cite=(index:number,place:string)=>refs[index]?<sup id={`cite-${index+1}-${place}`}><a href={`#ref-${refs[index].id}`} aria-label={`Reference ${index+1}`}>[{index+1}]</a></sup>:null;

  return <><ArticleProgress/><main id="main-content" className="article-page"><article>
    <header className="article-header"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href={article.kind==="effect"?"/effects":"/explore"}>{article.kind==="effect"?"Effects":"Explore"}</Link><span>/</span><span>{article.title}</span></nav><p className="kicker">{article.category}</p><h1>{article.title}</h1><p className="definition">{article.definition}</p><div className="tag-row article-tags">{article.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="article-meta"><span>{minutes} min read</span><span>Updated {new Date(article.updated+"T12:00:00").toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}</span><BookmarkButton slug={article.slug}/></div><ReadingControls/></header>
    <div className="article-layout"><div className="article-body" data-article-body>
      <section className="at-glance"><span>At a glance</span><p>{article.definition} The useful question is not “does this label fit?” but “under which conditions does this pattern become more or less likely?”</p><div className="glance-grid"><div><b>Core process</b><p>{article.mechanism}</p></div><div><b>Important limit</b><p>{article.limitation}</p></div></div></section>

      <section><AnchorHeading id="why-it-matters">Why it matters</AnchorHeading><p>{article.title} matters because subtle changes in context can alter what people notice, remember, feel, or choose—often without producing a vivid sense that anything changed. In {article.category.toLowerCase()}, that gap between experience and process can affect everyday decisions as well as how we interpret other people.</p><p>The concept is most valuable when it improves a process: a better question, a fairer comparison, a clearer environment, or a more realistic expectation. It becomes less useful when it is treated as a personality label or a complete explanation.</p></section>

      <section><AnchorHeading id="everyday-example">An everyday case</AnchorHeading><div className="case-study"><p className="case-label">Case notebook</p><p>{article.example}</p><div className="case-questions"><div><span>01</span><p><b>The quick interpretation</b>The outcome reflects a stable preference, ability, or character trait.</p></div><div><span>02</span><p><b>The research-minded interpretation</b>{article.mechanism} Other explanations still need to be considered.</p></div></div></div><p>This case is illustrative rather than diagnostic. The same outward behavior can have many causes, and a person may show the pattern in one setting but not another. A psychological concept should widen inquiry before it narrows a conclusion.</p></section>

      <section><AnchorHeading id="how-it-works">How the process may unfold</AnchorHeading><p>{article.mechanism} Researchers treat this as a proposed mechanism—a causal account that must be distinguished from merely renaming the observed behavior.</p><ol className="mechanism-steps"><li><span>1</span><div><b>A cue becomes relevant</b><p>A goal, expectation, prior belief, social signal, or feature of the environment changes what information is easiest to use.</p></div></li><li><span>2</span><div><b>Information is selected or weighted</b><p>Some evidence receives more attention, rehearsal, or subjective importance than competing information.</p></div></li><li><span>3</span><div><b>A response emerges</b><p>The resulting judgment, feeling, memory report, or action reflects both that weighting and the person’s knowledge, goals, and situation.</p></div></li></ol><aside className="evidence-note"><b>Mechanism is not destiny</b><p>More than one process may produce the same result. Incentives, expertise, emotion, culture, and task design can change which explanation fits best.</p></aside></section>

      <section><AnchorHeading id="research">Inside the research</AnchorHeading><p>{profile.setup} {cite(0,"research")}</p><div className="study-blueprint"><div><span>What is measured</span><p>{profile.measure}</p></div><div><span>What is compared</span><p>{profile.comparison}</p></div><div><span>What can be concluded</span><p>{profile.interpretation}</p></div></div><p>A well-designed study separates the proposed cause from plausible alternatives. Researchers also inspect effect size and uncertainty: a consistent average difference can be scientifically informative while still being too small or variable to predict one person accurately.</p></section>

      <section><AnchorHeading id="findings">What the evidence suggests</AnchorHeading><p>The evidence base is not one monolithic verdict. It contains experiments, reviews, replications, and disagreements about measurement or interpretation. The most responsible summary starts with what each source directly supports:</p><ul className="evidence-list">{refs.map((ref,index)=><li key={ref.id}><span>{String(index+1).padStart(2,"0")}</span><p>{ref.supports} {cite(index,"finding")}</p></li>)}</ul><p>Together, these sources support treating {article.title.toLowerCase()} as a bounded research concept rather than a universal law. Confidence should be greatest near the studied tasks and populations; applying the idea to schools, relationships, workplaces, health, or policy adds assumptions that deserve testing.</p></section>

      <section><AnchorHeading id="contexts">Where the pattern may appear</AnchorHeading><div className="context-grid">{profile.contexts.map((context,index)=><article key={context.title}><span>0{index+1}</span><h3>{context.title}</h3><p>{context.detail}</p></article>)}</div><p>These are plausible contexts, not proof that {article.title.toLowerCase()} caused a particular outcome. Look for the defining conditions, compare alternatives, and ask what observation would change your interpretation.</p></section>

      <section><AnchorHeading id="limits">Boundary conditions and open questions</AnchorHeading><p>{article.limitation} {cite(0,"limits")}</p><div className="limits-panel"><h3>Before generalizing, ask:</h3><ul><li>Was the effect observed in a controlled task, a natural setting, or both?</li><li>Does the sample resemble the people in the claim?</li><li>Would a different measure capture the same construct?</li><li>How large and precise was the estimate—not merely whether it crossed a significance threshold?</li><li>Have independent teams observed the pattern under comparable conditions?</li></ul></div><p>Culture, incentives, expertise, wording, measurement quality, and sampling can all matter. A failed replication may reveal noise, a missing condition, or a weak original result; a successful replication strengthens repeatability but does not by itself establish every explanation or application.</p></section>

      <section><AnchorHeading id="misconceptions">Common misconceptions</AnchorHeading><div className="myth-grid"><div><span>Myth</span><h3>“Knowing the name makes me immune.”</h3><p>Recognition can prompt a pause, but insight alone rarely removes a learned response or judgment tendency. Better decision environments and feedback often matter more.</p></div><div><span>Myth</span><h3>“This explains why that person behaved that way.”</h3><p>The concept generates hypotheses; it does not provide private access to another person’s motives or justify confident armchair diagnosis.</p></div><div><span>Myth</span><h3>“If an effect is real, it should happen every time.”</h3><p>Psychological research usually estimates changes in probability or average performance. Variation is expected, not evidence that the whole topic is meaningless.</p></div><div><span>Myth</span><h3>“A classic demonstration settles the issue.”</h3><p>Memorable studies begin conversations. Strong conclusions depend on measurement quality, replications, synthesis, and evidence outside a single paradigm.</p></div></div></section>

      <section><AnchorHeading id="practical">Putting the idea to work</AnchorHeading><p>The aim is not to police every thought. Use the concept at moments when the stakes, uncertainty, or opportunity for a better process justify the effort.</p><ol className="practice-list">{profile.practices.map((practice,index)=><li key={practice}><span>{index+1}</span><p>{practice}</p></li>)}</ol><div className="reflection"><b>A small field experiment</b><p>Choose one recurring situation in the next week. Record what you expected, what cue you noticed, what you decided, and what happened. The goal is not to prove the effect applies to you—it is to make the process observable enough to learn from.</p></div></section>

      <section><AnchorHeading id="related">Related concepts and distinctions</AnchorHeading><div className="distinction-list">{related.map(item=><Link href={articlePath(item)} key={item.slug}><div><b>{item.title}</b><p>{item.definition}</p></div><span>Compare →</span></Link>)}</div><p>Related concepts often overlap at the level of outcome but differ in mechanism. Distinguishing them requires asking what information changed, when it changed, and which response was measured.</p></section>

      <section><AnchorHeading id="takeaways">Key takeaways</AnchorHeading><ul className="takeaway-list"><li>{article.definition}</li><li>{article.mechanism}</li><li>{article.limitation}</li><li>Study design and measurement determine how far a conclusion can travel.</li><li>Use the idea as a qualified lens for improving a process—never as a diagnosis or total explanation.</li></ul><div className="reflection final-question"><b>A question to carry with you</b><p>Where might {article.title.toLowerCase()} change the questions you ask, even if it does not change your conclusion?</p></div></section>

      <section className="article-references"><AnchorHeading id="references">References</AnchorHeading>{refs.map((ref,index)=><div id={`ref-${ref.id}`} key={ref.id}><span>{index+1}</span><p>{ref.authors} ({ref.year}). <a href={ref.url} target="_blank" rel="noreferrer">{ref.title}</a>. <i>{ref.source}</i>.<small>{ref.type} · {ref.supports} <a className="back-citation" href={`#cite-${index+1}-finding`} aria-label={`Back to citation ${index+1}`}>↩ Back to text</a></small></p></div>)}</section>
    </div><aside className="toc"><p>In this article</p>{[["why-it-matters","Why it matters"],["everyday-example","Everyday case"],["how-it-works","How it works"],["research","Inside the research"],["findings","Evidence"],["contexts","Where it appears"],["limits","Limitations"],["misconceptions","Misconceptions"],["practical","Practical use"],["related","Related concepts"],["takeaways","Takeaways"],["references","References"]].map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}</aside></div>
  </article><section className="related"><p className="kicker">Continue exploring</p><h2>Follow the connection</h2><div className="article-grid">{related.map(a=><Link className="article-card" href={articlePath(a)} key={a.slug}><span>{a.category}</span><h3>{a.title}</h3><p>{a.definition}</p><b>Read next →</b></Link>)}</div></section></main></>
}
