"use client";

import { useEffect, useState } from "react";
import type { Article } from "@/lib/content";

export function ArticleProgress() { const [value,setValue]=useState(0); useEffect(()=>{const update=()=>{const el=document.querySelector<HTMLElement>("[data-article-body]");if(!el)return;const start=el.offsetTop;const end=start+el.offsetHeight-innerHeight;setValue(end<=start?100:Math.max(0,Math.min(100,((scrollY-start)/Math.max(1,end-start))*100)))};update();addEventListener("scroll",update,{passive:true});addEventListener("resize",update);return()=>{removeEventListener("scroll",update);removeEventListener("resize",update)}},[]);return <div className="progress-track" role="progressbar" aria-label="Article reading progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(value)}><span style={{width:`${value}%`}}/></div> }
export function BookmarkButton({slug}:{slug:string}) { const [saved,setSaved]=useState(false); useEffect(()=>{const id=setTimeout(()=>setSaved(JSON.parse(localStorage.getItem("mind-atlas-saved")||"[]").includes(slug)),0);return()=>clearTimeout(id)},[slug]); const toggle=()=>{const all:string[]=JSON.parse(localStorage.getItem("mind-atlas-saved")||"[]");const next=saved?all.filter(x=>x!==slug):[...all,slug];localStorage.setItem("mind-atlas-saved",JSON.stringify(next));setSaved(!saved);dispatchEvent(new Event("mind-atlas-saved"))};return <button className={`round-tool ${saved?"saved":""}`} onClick={toggle} aria-pressed={saved}>{saved?"♥ Saved":"♡ Save"}</button> }
export function ReadingControls(){const [large,setLarge]=useState(false);const [focus,setFocus]=useState(false);const [copied,setCopied]=useState(false);return <div className="article-actions"><button className="round-tool" onClick={()=>{setLarge(!large);document.documentElement.classList.toggle("large-text")}} aria-pressed={large}>A<span>A</span></button><button className="round-tool" onClick={()=>{setFocus(!focus);document.documentElement.classList.toggle("focus-mode")}} aria-pressed={focus}>◫ Focus</button><button className="round-tool" onClick={async()=>{await navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),1600)}}>{copied?"✓ Copied":"↗ Share"}</button></div>}
export function SavedGrid({items}:{items:Article[]}){const [slugs,setSlugs]=useState<string[]>([]);useEffect(()=>{const load=()=>setSlugs(JSON.parse(localStorage.getItem("mind-atlas-saved")||"[]"));const id=setTimeout(load,0);addEventListener("mind-atlas-saved",load);return()=>{clearTimeout(id);removeEventListener("mind-atlas-saved",load)}},[]);const saved=items.filter(a=>slugs.includes(a.slug));return saved.length?<div className="article-grid">{saved.map(a=><div className="article-card" key={a.slug}><h2>{a.title}</h2><p>{a.definition}</p><div className="saved-card-actions"><a href={a.kind==="effect"?`/effects/${a.slug}`:`/articles/${a.slug}`}>Continue reading →</a><BookmarkButton slug={a.slug}/></div></div>)}</div>:<div className="empty-state"><span>♡</span><h2>Your reading shelf is empty</h2><p>Save an article and it will appear here. Saves stay in this browser and do not sync between devices.</p><a className="primary-button" href="/explore">Explore the library <span>→</span></a></div>}
