import type { Article } from "./content";

export type ArticleSpecifics = {
  focus: string;
  everydaySignal: string;
  quickMisread: string;
  betterQuestion: string;
  process: { title: string; detail: string }[];
  researchAngle: string;
  boundary: string;
  myths: { myth: string; reality: string }[];
  practiceIntro: string;
  fieldTest: string;
  finalQuestion: string;
};

type ArticleAngle = Omit<ArticleSpecifics, "process" | "myths">;

const angles: Record<string, ArticleAngle> = {
  "confirmation-bias": {
    focus: "Confirmation bias is most useful for spotting how a question, search strategy, or trusted source can quietly narrow the evidence you let count.",
    everydaySignal: "Watch for moments when supporting examples feel abundant while contrary cases feel nitpicky, irrelevant, or unusually easy to explain away.",
    quickMisread: "The tempting read is that a person is simply closed-minded; the more precise read is that their evidence pipeline may be filtering what reaches serious consideration.",
    betterQuestion: "What would I expect to see if my current belief were wrong, and have I looked for that evidence in a place where it could actually appear?",
    researchAngle: "The strongest demonstrations separate prior belief from the quality of new information, then measure whether people search, interpret, or remember asymmetrically.",
    boundary: "The pattern weakens when accuracy is rewarded, when disconfirming evidence is concrete, or when people commit to evaluation criteria before seeing the result.",
    practiceIntro: "Use it when a belief has practical consequences: forecasts, hiring, diagnosis, product choices, or conflict narratives.",
    fieldTest: "Before reading about a disputed topic, write one observation that would change your mind and one source likely to contain it. Check that source before returning to familiar commentary.",
    finalQuestion: "Which belief in your week deserves a real chance to surprise you?",
  },
  anchoring: {
    focus: "Anchoring matters whenever an opening number becomes the mental starting line for what later feels expensive, likely, fair, or realistic.",
    everydaySignal: "Look for first estimates, list prices, suggested donations, deadline guesses, or salary bands that enter the room before independent judgment does.",
    quickMisread: "It is easy to treat the final number as carefully reasoned when part of it may simply be insufficient movement away from the first number seen.",
    betterQuestion: "What estimate would I make if I had not seen the starting value, and what base rate should constrain that estimate?",
    researchAngle: "Anchoring studies are clearest when the anchor is arbitrary or experimentally assigned, because the design can show movement caused by the starting value itself.",
    boundary: "Expertise, relevant feedback, wide ranges, and independent pre-estimates can reduce anchoring, but even knowledgeable people can be pulled by plausible anchors.",
    practiceIntro: "Use it in negotiation, planning, pricing, forecasting, and any meeting where the first number may become the room's gravity.",
    fieldTest: "For the next estimate you make, write a low, middle, and high value before seeing anyone else's number. Compare how much the conversation moves you.",
    finalQuestion: "What number entered the conversation before anyone earned it?",
  },
  "availability-heuristic": {
    focus: "Availability is about the difference between what is easy to recall and what is actually common, dangerous, or representative.",
    everydaySignal: "Notice when vivid stories, recent headlines, or emotionally sticky examples make a risk feel larger than duller base rates suggest.",
    quickMisread: "The quick read is that a feeling of frequency proves the event is frequent; the better read is that memory fluency needs calibration.",
    betterQuestion: "Am I estimating from a sample of reality or from a sample of what has been vivid, recent, repeated, or discussed around me?",
    researchAngle: "Useful studies compare subjective estimates with manipulated recall ease, recency, vividness, or exposure while tracking actual frequencies separately.",
    boundary: "Availability can be a good cue when your memory sample is broad and representative; it misleads most when exposure is skewed.",
    practiceIntro: "Use it when reacting to news, safety decisions, investing stories, medical anecdotes, or any situation where one example dominates attention.",
    fieldTest: "When a risk feels suddenly common, write down the last three places you encountered examples of it, then look for a boring denominator.",
    finalQuestion: "Is this estimate coming from frequency, or from fluency?",
  },
  representativeness: {
    focus: "Representativeness helps explain why a story that fits a prototype can feel more probable than a dull base rate.",
    everydaySignal: "Watch for judgments built around resemblance: the person sounds like an entrepreneur, the startup looks like a winner, the symptom pattern feels classic.",
    quickMisread: "A matching description can be mistaken for strong probability evidence even when the category itself is rare or the sample is tiny.",
    betterQuestion: "What is the base rate before I inspect the resemblance, and how diagnostic is this resemblance compared with alternatives?",
    researchAngle: "Classic tasks contrast prototype-rich descriptions with base-rate information to see which cue dominates probability judgments.",
    boundary: "Similarity is not useless; it becomes risky when it crowds out sample size, prior probability, and the reliability of the description.",
    practiceIntro: "Use it when screening candidates, reading profiles, interpreting symptoms, or making probability judgments from a narrative.",
    fieldTest: "For one classification decision, write the boring base rate first, then list what the story adds beyond resemblance.",
    finalQuestion: "What would this look like if the stereotype fit but the probability did not?",
  },
  "framing-effect": {
    focus: "Framing matters because equivalent facts can invite different reference points, emotions, and goals.",
    everydaySignal: "Look for survival versus mortality, savings versus losses, opt-in versus opt-out, or any wording that changes what feels like the default comparison.",
    quickMisread: "A changed preference can look like a changed value when it may be a changed frame around the same underlying tradeoff.",
    betterQuestion: "Can I restate the same option in the opposite frame and still endorse the choice?",
    researchAngle: "The cleanest framing evidence holds outcomes constant while altering wording, then checks whether choices move with the presentation.",
    boundary: "Frames are not always truly equivalent; wording can convey norms, trust, agency, or omitted information that changes the decision itself.",
    practiceIntro: "Use it in health choices, product copy, policy debates, performance metrics, and personal decisions with gains and losses.",
    fieldTest: "Rewrite one decision as both a gain and a loss statement. If your preference changes, identify which reference point moved.",
    finalQuestion: "What frame is doing work before the facts are even considered?",
  },
  "loss-aversion": {
    focus: "Loss aversion is most revealing when giving something up feels more intense than receiving the same thing would feel good.",
    everydaySignal: "Notice reluctance to sell, switch, cancel, renegotiate, or experiment because the possible loss is vivid and the possible gain feels abstract.",
    quickMisread: "It can look like a stable preference for the status quo when the real driver is the reference point that defines something as a loss.",
    betterQuestion: "If I did not already have this option, would I pay the same cost to acquire it now?",
    researchAngle: "Research often manipulates ownership, reference points, or gain-loss descriptions to test whether equivalent outcomes receive asymmetric weight.",
    boundary: "Loss aversion varies with stakes, experience, liquidity, framing, and whether gains and losses are genuinely comparable.",
    practiceIntro: "Use it when evaluating subscriptions, investments, negotiations, habits, and plans that survive mainly because change feels like loss.",
    fieldTest: "Pick one thing you are reluctant to give up. Price it from the buyer's side and from the owner's side, then compare the gap.",
    finalQuestion: "Which reference point is making this feel like a loss?",
  },
  "sunk-cost-effect": {
    focus: "The sunk cost effect is about past investment sneaking into decisions that should be governed by future value.",
    everydaySignal: "Listen for 'after all this time,' 'we already paid,' or 'it would be wasteful to stop' when the remaining path still looks poor.",
    quickMisread: "Persistence can look disciplined even when the argument is mostly about justifying costs that cannot be recovered.",
    betterQuestion: "If this were offered to me today with no history attached, would I choose the remaining costs and benefits?",
    researchAngle: "Good tests distinguish rational persistence from escalation by comparing choices with identical future payoffs but different histories of investment.",
    boundary: "Continuing can be sensible when finishing creates learning, reputation value, contractual options, or new future benefits.",
    practiceIntro: "Use it for projects, subscriptions, relationships with plans, long queues, unread books, and any investment with a painful exit.",
    fieldTest: "Write a fresh-start decision memo for one lingering commitment: only future costs, benefits, and learning count.",
    finalQuestion: "What would you choose if the past could not vote?",
  },
  "hindsight-bias": {
    focus: "Hindsight bias matters because outcomes can rewrite the feeling of what was knowable before the outcome occurred.",
    everydaySignal: "Watch for 'obviously,' 'we should have known,' or tidy stories that appear only after a success, failure, diagnosis, or market move.",
    quickMisread: "A coherent after-the-fact story can be mistaken for evidence that the result was predictable at the time.",
    betterQuestion: "What did we actually forecast beforehand, and what plausible outcomes did we consider then?",
    researchAngle: "Studies compare foresight judgments with hindsight judgments after participants learn an outcome, often revealing inflated perceived predictability.",
    boundary: "Some outcomes really were foreseeable; the bias is in overstating certainty, not in learning from warning signs.",
    practiceIntro: "Use it in retrospectives, performance reviews, investing, medical decisions, and postmortems after dramatic outcomes.",
    fieldTest: "Before a decision resolves, record probabilities for three outcomes. Revisit the note after the result feels obvious.",
    finalQuestion: "What uncertainty existed before the ending made a story?",
  },
  overconfidence: {
    focus: "Overconfidence is about confidence outrunning accuracy, range width, or the amount of feedback a domain can support.",
    everydaySignal: "Notice narrow timelines, precise forecasts, certain diagnoses, or confident claims in domains with sparse feedback and hidden dependencies.",
    quickMisread: "Confidence can be mistaken for competence when the task has not provided enough valid feedback to calibrate certainty.",
    betterQuestion: "What would my confidence be if I had to name the missing information, failure modes, and outside-view base rate?",
    researchAngle: "Calibration tasks compare stated confidence or intervals against actual accuracy across many judgments.",
    boundary: "Confidence can be warranted in domains with repeated practice, clear feedback, and stable rules.",
    practiceIntro: "Use it when planning projects, estimating knowledge, forecasting demand, or interpreting strong opinions.",
    fieldTest: "Make ten small predictions with confidence levels this week. Score them later and see whether 70 percent confidence lands near 70 percent accuracy.",
    finalQuestion: "Is your certainty calibrated by feedback or inflated by familiarity?",
  },
  "dunning-kruger-effect": {
    focus: "The Dunning-Kruger effect is best treated as a question about skill, feedback, and self-evaluation, not a punchline about foolish people.",
    everydaySignal: "Look for beginners who cannot yet see the standards by which their work will be judged, especially when feedback is vague.",
    quickMisread: "The popular misread is that low-skill people are uniquely arrogant; the research question is narrower and measurement-sensitive.",
    betterQuestion: "Does this person have access to the criteria, examples, and feedback needed to judge performance accurately?",
    researchAngle: "The key issue is whether performance and self-assessment move together after accounting for measurement error, regression, and task design.",
    boundary: "The effect does not imply that every novice is overconfident or that experts are always humble.",
    practiceIntro: "Use it carefully in training, hiring, mentoring, and self-assessment where clear standards can improve calibration.",
    fieldTest: "Before judging your skill in a new area, compare your work with three expert examples and write the differences you can now see.",
    finalQuestion: "What standard would make your self-assessment less impressionistic?",
  },
  "selective-attention": {
    focus: "Selective attention is the everyday fact that goals, salience, and capacity decide what earns processing priority.",
    everydaySignal: "Notice when one task makes other sounds, cues, or social signals fade even though they remain physically present.",
    quickMisread: "Missing information can look careless when attention was already committed to a competing goal.",
    betterQuestion: "What was the person trying to monitor, and what cues were made easy or hard to select?",
    researchAngle: "Experiments manipulate task goals, cue salience, load, and distractors to see what reaches awareness or changes response speed.",
    boundary: "Unattended does not mean unprocessed, and attention can shift quickly when a cue becomes meaningful.",
    practiceIntro: "Use it for interface design, studying, meetings, safety checks, and any environment with competing signals.",
    fieldTest: "During one focused task, list what you intend to monitor and what you are willing to ignore. Afterward, compare that with what actually broke through.",
    finalQuestion: "What is your environment training you to notice first?",
  },
  "inattentional-blindness": {
    focus: "Inattentional blindness shows how a visible event can fail to become a noticed event when attention is already loaded.",
    everydaySignal: "Watch for misses during driving, sports, editing, caregiving, or dashboard monitoring when a focal task feels demanding.",
    quickMisread: "The miss can look impossible or dishonest because observers assume visible means consciously seen.",
    betterQuestion: "What task consumed attention, and was the unexpected item relevant enough to break through it?",
    researchAngle: "Studies vary perceptual or cognitive load while measuring detection of unexpected objects or events.",
    boundary: "Salient, expected, dangerous, or goal-relevant events are more likely to be noticed; failures are not uniform.",
    practiceIntro: "Use it when designing safety routines, reviews, handoffs, and visual displays where a single miss matters.",
    fieldTest: "After completing a demanding visual task, pause for a deliberate second scan aimed only at unexpected changes or hazards.",
    finalQuestion: "What could be visible in your scene but absent from your task?",
  },
  "change-blindness": {
    focus: "Change blindness matters because people often store enough visual information for action, not a complete before-and-after record.",
    everydaySignal: "Look for missed edits, UI changes, moved objects, or swapped details after cuts, interruptions, popups, or glances away.",
    quickMisread: "A missed change can look like poor eyesight or indifference when the comparison process itself was disrupted.",
    betterQuestion: "Did the observer have attention on the changing feature at the moment a comparison was possible?",
    researchAngle: "Researchers introduce flickers, cuts, masks, or interruptions to test whether substantial scene changes are detected.",
    boundary: "Changes to goal-relevant, attended, or semantically important features are often detected quickly.",
    practiceIntro: "Use it for editing, QA, handoffs, driving, design reviews, and any workflow where changed details must be caught.",
    fieldTest: "After an interruption, rescan the area from top to bottom instead of resuming from memory.",
    finalQuestion: "What changed while your attention was busy bridging the gap?",
  },
  "stroop-effect": {
    focus: "The Stroop effect reveals conflict between a practiced automatic response and the task you are deliberately trying to perform.",
    everydaySignal: "Notice interference when labels, habits, defaults, or familiar meanings compete with a current instruction.",
    quickMisread: "Slowness can look like lack of knowledge when the real issue is response conflict from an overlearned pathway.",
    betterQuestion: "Which response is automatic here, and how does the environment invite it before the intended response?",
    researchAngle: "Color-word tasks measure the cost of incongruent meanings by comparing speed and errors against congruent or neutral trials.",
    boundary: "Language fluency, practice, response mode, and timing equipment all shape the measured effect.",
    practiceIntro: "Use it when building forms, signs, training tasks, and workflows where old labels or defaults fight the desired action.",
    fieldTest: "Find one recurring error and ask whether the cue points to the old response more strongly than the instruction points to the new one.",
    finalQuestion: "What automatic response is your design accidentally cueing?",
  },
  "gestalt-grouping": {
    focus: "Gestalt grouping is about how layout turns separate marks into perceived units before deliberate interpretation begins.",
    everydaySignal: "Watch how proximity, similarity, alignment, borders, and motion make things feel related or unrelated at a glance.",
    quickMisread: "A confusing display may be blamed on user effort when the visual organization itself suggests the wrong relationships.",
    betterQuestion: "What does the arrangement imply before anyone reads the labels?",
    researchAngle: "Grouping research tests how visual cues such as proximity, similarity, continuity, closure, and common fate organize perception.",
    boundary: "Grouping cues compete with task goals, learned conventions, and context; they guide perception rather than dictate it.",
    practiceIntro: "Use it for dashboards, slides, forms, maps, diagrams, and any place where structure must be seen quickly.",
    fieldTest: "Blur or step back from a layout and name the groups you perceive before reading. Adjust spacing before adding explanation.",
    finalQuestion: "What relationships does the page show before it says anything?",
  },
  "working-memory": {
    focus: "Working memory matters whenever a task requires holding pieces in mind while transforming, comparing, or coordinating them.",
    everydaySignal: "Notice errors after interruptions, multi-step instructions, mental math, dense forms, or conversations with too many unresolved threads.",
    quickMisread: "Forgetting a step can look like low effort when the active workspace was overloaded or poorly supported.",
    betterQuestion: "Which items must be maintained, which must be manipulated, and what can be moved into the environment?",
    researchAngle: "Studies separate storage, attention control, interference, and manipulation demands rather than treating capacity as one fixed number.",
    boundary: "Chunking, expertise, meaningful structure, and external aids can dramatically change effective capacity.",
    practiceIntro: "Use it when studying, designing instructions, planning meetings, debugging, or helping someone execute a sequence.",
    fieldTest: "Take one cognitively heavy task and externalize the intermediate states: checklist, scratchpad, diagram, or visible queue.",
    finalQuestion: "What are you asking your mind to hold that the environment could hold better?",
  },
  "reconstructive-memory": {
    focus: "Reconstructive memory frames remembering as rebuilding from traces, cues, schemas, and present purposes.",
    everydaySignal: "Watch for sincere disagreements about shared events, details that sharpen after retelling, or memories shaped by later context.",
    quickMisread: "A changed memory can look like lying when the person may be reconstructing from partial information.",
    betterQuestion: "What cues, expectations, or later conversations could be helping build this version of the memory?",
    researchAngle: "Researchers examine how schemas, wording, source cues, and retrieval context alter what people report later.",
    boundary: "Reconstruction does not make memory worthless; many memories remain accurate enough for their practical use.",
    practiceIntro: "Use it for conflict, interviews, notes, retrospectives, and any setting where details matter after time has passed.",
    fieldTest: "Record important observations before discussion, then mark later additions as interpretations rather than original memory.",
    finalQuestion: "Which parts of this memory are trace, cue, and story?",
  },
  "misinformation-effect": {
    focus: "The misinformation effect shows how post-event wording or suggestions can become entangled with later reports.",
    everydaySignal: "Listen for leading questions, repeated retellings, confident corrections, or details introduced after the original event.",
    quickMisread: "A later false detail can look fabricated when it may reflect source confusion between event memory and post-event information.",
    betterQuestion: "Did this detail come from the event itself, or from a question, conversation, image, or assumption afterward?",
    researchAngle: "Studies expose participants to an event and then vary misleading post-event information before testing later memory reports.",
    boundary: "Effects vary with delay, attention, confidence, age, wording, and whether the original detail was strongly encoded.",
    practiceIntro: "Use it in interviews, eyewitness discussions, incident reviews, classroom recall, and family stories.",
    fieldTest: "When collecting an account, ask open questions first and postpone specific alternatives until after the person's free recall.",
    finalQuestion: "What detail entered the memory after the moment had passed?",
  },
  "serial-position-effects": {
    focus: "Serial-position effects remind us that where information appears in a sequence changes its odds of being remembered.",
    everydaySignal: "Notice first and last agenda items, errands, candidates, or talking points getting more recall than the middle.",
    quickMisread: "A forgotten middle item can look less important when it may simply have had the weakest position in the sequence.",
    betterQuestion: "Was this information placed where attention, rehearsal, or recency would support it?",
    researchAngle: "Free-recall studies vary list length, timing, distraction, and output order to trace primacy and recency patterns.",
    boundary: "Distinctiveness, meaning, rehearsal strategy, and delayed testing can change or erase the classic curve.",
    practiceIntro: "Use it for presentations, study plans, onboarding, menus, interviews, and memory-heavy communication.",
    fieldTest: "Move one crucial middle item to the opening summary and closing recap, then check recall later.",
    finalQuestion: "What important idea is stranded in the middle?",
  },
  "spacing-effect": {
    focus: "The spacing effect matters because durable learning often grows from repeated retrieval across time, not one long exposure.",
    everydaySignal: "Watch for material that feels fluent after cramming but disappears days later.",
    quickMisread: "Immediate ease can be mistaken for long-term learning when it may reflect short-term familiarity.",
    betterQuestion: "When will I need this again, and what review interval makes retrieval effortful but possible?",
    researchAngle: "Spacing studies compare equal total study time distributed across different intervals and test later retention.",
    boundary: "The best gap depends on retention goal, prior knowledge, material difficulty, and feedback opportunities.",
    practiceIntro: "Use it for exams, skills, names, procedures, languages, and any knowledge that must survive beyond today.",
    fieldTest: "Split one study block into three short sessions across the week and test yourself before each review.",
    finalQuestion: "Are you practicing for today's fluency or next month's access?",
  },
  "retrieval-practice": {
    focus: "Retrieval practice turns memory into an active attempt to produce knowledge, revealing and strengthening access routes.",
    everydaySignal: "Notice the difference between rereading something that feels familiar and explaining it without looking.",
    quickMisread: "Struggle during recall can feel like failure even when it is the productive work that improves later retention.",
    betterQuestion: "Can I produce the idea, solve the problem, or explain the distinction before checking the source?",
    researchAngle: "Research compares restudy with testing or free recall, often showing stronger delayed retention after successful retrieval with feedback.",
    boundary: "Poor questions, no feedback, excessive difficulty, or mismatch with the final task can limit benefits.",
    practiceIntro: "Use it for classes, documentation, presentations, skill drills, and learning from reading.",
    fieldTest: "After one article or chapter, close it and write five claims from memory. Reopen only to correct and sharpen them.",
    finalQuestion: "What can you retrieve, not just recognize?",
  },
  "classical-conditioning": {
    focus: "Classical conditioning is prediction learning: cues gain power when they reliably signal meaningful outcomes.",
    everydaySignal: "Look for sounds, places, smells, notifications, or routines that trigger anticipation before anything has happened yet.",
    quickMisread: "It is often misread as simple pairing, when timing, prediction error, context, and meaning all matter.",
    betterQuestion: "What outcome does this cue predict, and how reliable is that prediction in this context?",
    researchAngle: "Conditioning studies examine how responses change when cues predict, stop predicting, or ambiguously predict significant events.",
    boundary: "Responses can extinguish, renew in old contexts, generalize to similar cues, or depend on biological relevance.",
    practiceIntro: "Use it to understand habits around notifications, anxiety triggers, brand cues, food responses, and therapeutic exposure.",
    fieldTest: "Identify one cue that changes your state, then track what outcome usually follows it and whether the association still fits reality.",
    finalQuestion: "What has this cue taught your body to expect?",
  },
  "operant-conditioning": {
    focus: "Operant conditioning looks at how consequences shape the future probability of actions.",
    everydaySignal: "Notice behaviors maintained by praise, relief, convenience, attention, avoidance, points, streaks, or intermittent wins.",
    quickMisread: "A behavior can look like a fixed trait when its consequences are quietly sustaining it.",
    betterQuestion: "What happens immediately after the behavior that makes it more or less likely next time?",
    researchAngle: "Researchers vary reinforcement, punishment, timing, and schedules to see how behavior changes across repeated opportunities.",
    boundary: "Human behavior also reflects goals, interpretation, identity, norms, and intrinsic motives, not consequences alone.",
    practiceIntro: "Use it for classroom routines, product loops, team norms, health behavior, and personal habit design.",
    fieldTest: "For one recurring behavior, write the immediate payoff and the delayed cost. Change the immediate consequence first.",
    finalQuestion: "What consequence is training this behavior?",
  },
  "observational-learning": {
    focus: "Observational learning explains how people pick up actions, norms, and expectations by watching others.",
    everydaySignal: "Look for newcomers copying meeting tone, children imitating adults, or users learning an app by watching peers.",
    quickMisread: "Imitation can look automatic, but attention, memory, ability, motivation, and perceived consequences all shape it.",
    betterQuestion: "Who is being treated as the model, what outcome do observers see, and is the action reproducible?",
    researchAngle: "Studies manipulate modeled behavior and consequences, then measure later imitation or adaptation.",
    boundary: "People do not copy everything they see; they interpret models through status, similarity, values, and context.",
    practiceIntro: "Use it in onboarding, parenting, leadership, social media, classrooms, and culture change.",
    fieldTest: "Choose one norm you want to spread and make a respected model perform it visibly with clear consequences.",
    finalQuestion: "What behavior is being taught by example rather than instruction?",
  },
  conformity: {
    focus: "Conformity matters when group consensus changes what someone says, does, or even inspects as evidence.",
    everydaySignal: "Watch for silence after unanimity, laughter that arrives late, softened disagreement, or private doubts hidden by public alignment.",
    quickMisread: "Agreement can look like independent consensus when it may reflect informational uncertainty or social pressure.",
    betterQuestion: "Would the same judgment appear if people answered privately before hearing the group?",
    researchAngle: "Conformity research manipulates unanimity, ambiguity, public response, and group size to separate informational and normative influence.",
    boundary: "Conformity varies across cultures, stakes, expertise, group meaning, and whether dissent is made legitimate.",
    practiceIntro: "Use it in meetings, juries, classrooms, product reviews, and any setting where visible consensus forms quickly.",
    fieldTest: "Collect independent written judgments before discussion, then compare how the conversation changes them.",
    finalQuestion: "Is this consensus independent, or did it form in public?",
  },
  obedience: {
    focus: "Obedience focuses on how authority, roles, and responsibility structures can make harmful or questionable actions easier to perform.",
    everydaySignal: "Listen for 'I was told to,' 'that's the procedure,' or discomfort being overridden by hierarchy.",
    quickMisread: "Obedience is often misread as blind submission, when people interpret authority, context, legitimacy, and exit options.",
    betterQuestion: "What authority signals, role expectations, and responsibility shifts are shaping the choice?",
    researchAngle: "Research varies authority presence, proximity to consequences, institutional setting, and opportunities to refuse.",
    boundary: "Refusal is common and meaningful; historical, cultural, and situational details change what the classic studies imply.",
    practiceIntro: "Use it in ethics training, medicine, organizations, compliance systems, and any setting with strong hierarchy.",
    fieldTest: "For one procedure, define a legitimate stop signal and escalation path before pressure arrives.",
    finalQuestion: "Where does responsibility actually sit in this chain of instruction?",
  },
  "social-proof": {
    focus: "Social proof is the shortcut of treating other people's behavior as evidence about what is correct, safe, or worth doing.",
    everydaySignal: "Notice popularity badges, long lines, review counts, trending posts, and everyone-else-is-doing-it arguments.",
    quickMisread: "Popularity can be mistaken for quality when it may reflect imitation, visibility, convenience, or early luck.",
    betterQuestion: "What information might the crowd have, and what non-informational reasons could explain the same crowd?",
    researchAngle: "Studies and field data examine how visible choices change later choices while trying to separate information from herd dynamics.",
    boundary: "Crowds are more informative when members are independent, knowledgeable, and facing similar goals.",
    practiceIntro: "Use it for consumer choices, platform design, public behavior, fundraising, and social norms campaigns.",
    fieldTest: "Before following a crowd, name one reason it might be informed and one reason it might be copying itself.",
    finalQuestion: "Is the crowd evidence, influence, or both?",
  },
  "bystander-effect": {
    focus: "The bystander effect is about how responsibility and interpretation change when other observers are present.",
    everydaySignal: "Watch for hesitation in ambiguous moments: everyone looks around, assumes someone else knows, or waits for a clearer signal.",
    quickMisread: "Non-helping can look like apathy when ambiguity, social checking, and diffusion of responsibility may be doing the work.",
    betterQuestion: "Is the need clear, and has one person been given a specific role?",
    researchAngle: "Research manipulates group presence, danger, ambiguity, and communication to see when helping decreases or increases.",
    boundary: "Dangerous, clearly serious emergencies can reduce ambiguity and sometimes make groups more helpful.",
    practiceIntro: "Use it for safety planning, public spaces, online moderation, medical response, and team responsibility.",
    fieldTest: "In a group task, assign one named person to one next action instead of asking whether someone can handle it.",
    finalQuestion: "Who, specifically, owns the next helpful action?",
  },
  "social-facilitation": {
    focus: "Social facilitation explains why other people can sharpen well-learned responses and disrupt fragile ones.",
    everydaySignal: "Notice easier performance in races, rehearsed presentations, or routine tasks, but shakier execution during new or complex work.",
    quickMisread: "Audience effects can be mistaken for general confidence rather than the interaction between arousal and task mastery.",
    betterQuestion: "Is the dominant response here the right response, and how practiced is it under observation?",
    researchAngle: "Studies compare performance alone versus in the presence of others while separating simple, practiced, difficult, and novel tasks.",
    boundary: "Evaluation, coaction, audience expertise, skill level, and task type can all change the effect.",
    practiceIntro: "Use it in practice design, sports, performance reviews, classrooms, and public work sessions.",
    fieldTest: "Practice a difficult task privately until the right response is dominant, then add observers gradually.",
    finalQuestion: "Will an audience amplify the response you want or the one you have overlearned?",
  },
  "social-loafing": {
    focus: "Social loafing matters when pooled outcomes make individual effort hard to see or feel necessary.",
    everydaySignal: "Look for large groups, vague ownership, invisible contributions, and tasks where effort cannot be traced.",
    quickMisread: "Lower effort can look like laziness when the design has made contribution anonymous or seemingly dispensable.",
    betterQuestion: "Can each person see their unique contribution, and does the group need it to succeed?",
    researchAngle: "Researchers compare individual versus pooled performance while varying identifiability, group size, and task value.",
    boundary: "Cohesion, meaningful goals, visible roles, and small teams can reduce or reverse loafing.",
    practiceIntro: "Use it in group projects, volunteer teams, meetings, brainstorms, and shared operational work.",
    fieldTest: "For one group task, assign visible roles and show how each piece changes the final outcome.",
    finalQuestion: "Where has the group made individual effort invisible?",
  },
  "halo-effect": {
    focus: "The halo effect shows how one strong impression can spill into judgments that need separate evidence.",
    everydaySignal: "Notice attractive design, charisma, prestige, friendliness, or one standout success lifting ratings of unrelated qualities.",
    quickMisread: "A global good feeling can be mistaken for evidence about competence, honesty, rigor, or fit.",
    betterQuestion: "Which specific trait am I judging, and what evidence speaks to that trait directly?",
    researchAngle: "Halo research compares global impressions with ratings on distinct dimensions to see whether evaluations move together too easily.",
    boundary: "Strong diagnostic evidence can override a halo, and not every correlated rating is unjustified.",
    practiceIntro: "Use it in interviews, performance reviews, product evaluation, teaching, design critique, and media judgment.",
    fieldTest: "Score the most important criterion before looking at polish, status, or presentation quality.",
    finalQuestion: "What exactly earned this positive impression?",
  },
  "fundamental-attribution-error": {
    focus: "Attribution and context asks whether behavior is being explained by character while the situation stays underexamined.",
    everydaySignal: "Watch for quick labels such as lazy, rude, careless, or brilliant before constraints and incentives are known.",
    quickMisread: "A visible action can feel like a direct window into disposition when unseen pressures may explain much of it.",
    betterQuestion: "What would make the same behavior understandable from the actor's position?",
    researchAngle: "Attribution studies compare observer and actor perspectives, situational constraints, cultural context, and information availability.",
    boundary: "Dispositions can matter; the point is to test situational explanations before treating character as obvious.",
    practiceIntro: "Use it in conflict, management, teaching, customer support, and online interpretation.",
    fieldTest: "Before assigning a trait, list three constraints that could produce the same behavior in a reasonable person.",
    finalQuestion: "What part of the situation is invisible from your viewpoint?",
  },
  "ingroup-favoritism": {
    focus: "In-group favoritism is about preferential attention, trust, evaluation, or resources flowing toward people marked as us.",
    everydaySignal: "Notice benefit-of-the-doubt gaps, ambiguous calls judged by team loyalty, or opportunities circulating through familiar circles.",
    quickMisread: "Favoring insiders can appear as neutral merit judgment when group membership shaped what was noticed and forgiven.",
    betterQuestion: "Would the same evidence be judged the same way if it came from an out-group member?",
    researchAngle: "Studies manipulate group labels, status, competition, and norms to see when minimal or meaningful groups shift allocation and judgment.",
    boundary: "Favoritism does not always mean hostility; norms, status, accountability, and cross-cutting identities matter.",
    practiceIntro: "Use it for hiring, grading, moderation, fan behavior, team conflict, and institutional fairness.",
    fieldTest: "Blind one evaluation criterion or swap group labels in a written scenario and see whether your judgment moves.",
    finalQuestion: "Where does 'us' change the standard?",
  },
  "cognitive-dissonance": {
    focus: "Cognitive dissonance is the tension that can arise when actions, commitments, and beliefs pull against each other.",
    everydaySignal: "Watch for post-choice justification, defensive explanations, selective exposure, or new values appearing after a costly decision.",
    quickMisread: "A changed attitude can look like pure learning when it may also be reducing discomfort from inconsistency.",
    betterQuestion: "What commitment or self-image would be threatened if this evidence were taken seriously?",
    researchAngle: "Dissonance studies vary choice, effort, incentives, and public commitment to test when people revise beliefs or evaluations.",
    boundary: "Not every inconsistency hurts; self-relevance, culture, perceived choice, and consequences shape the response.",
    practiceIntro: "Use it in decisions, persuasion, habit change, moral conflict, and post-purchase reflection.",
    fieldTest: "After a hard choice, write what you gave up before building the case for what you chose.",
    finalQuestion: "What belief is protecting the choice, and what choice is protecting the belief?",
  },
  "emotion-regulation": {
    focus: "Emotion regulation is about changing the path of an emotional episode, not simply suppressing or conquering feeling.",
    everydaySignal: "Notice choices about situations, attention, interpretation, expression, and recovery after an emotion has already started.",
    quickMisread: "A strategy can be labeled healthy or unhealthy in the abstract when usefulness depends on timing, goal, intensity, and context.",
    betterQuestion: "Am I trying to change the situation, the meaning, the attention pattern, or the response?",
    researchAngle: "Research compares strategies such as reappraisal, distraction, acceptance, suppression, and situation selection across outcomes and contexts.",
    boundary: "No strategy wins everywhere; short-term relief, relationship goals, and long-term learning can point in different directions.",
    practiceIntro: "Use it for conflict, stress, performance, parenting, health behavior, and recovery from setbacks.",
    fieldTest: "For one recurring emotion, map where you can intervene before, during, and after the peak.",
    finalQuestion: "Which part of the emotional sequence is most changeable right now?",
  },
  "stress-appraisal": {
    focus: "Stress appraisal centers on how demands and perceived resources turn the same event into threat, challenge, or overload.",
    everydaySignal: "Notice when a task changes emotional tone after support, preparation, control, or stakes become clearer.",
    quickMisread: "Stress can be misread as purely caused by the event, ignoring how resources and meaning shape the response.",
    betterQuestion: "What demand is being appraised, and what coping resources are available or missing?",
    researchAngle: "Studies use self-report, physiology, performance, and interventions to examine how appraisals link situations to stress responses.",
    boundary: "Appraisal is not positive thinking; material conditions, chronic demands, and real constraints can dominate.",
    practiceIntro: "Use it in workload planning, presentations, caregiving, health decisions, and conflict preparation.",
    fieldTest: "Before a stressful event, write the demand, the resource gap, and one concrete support that would change the appraisal.",
    finalQuestion: "Is this a threat because of the demand, the resources, or both?",
  },
  "self-determination-theory": {
    focus: "Self-determination theory highlights how autonomy, competence, and relatedness shape the quality of motivation.",
    everydaySignal: "Look for persistence improving when people have meaningful choice, visible progress, and supportive connection.",
    quickMisread: "Autonomy is often mistaken for doing whatever you want, rather than acting with ownership inside real constraints.",
    betterQuestion: "Which need is supported or frustrated here: autonomy, competence, or relatedness?",
    researchAngle: "Research measures need support, motivation quality, engagement, and well-being across classrooms, work, health, and relationships.",
    boundary: "Needs can be expressed differently across cultures and settings; support does not mean absence of structure.",
    practiceIntro: "Use it for teaching, coaching, management, product design, health change, and personal goal setting.",
    fieldTest: "Take one goal you are avoiding and add one choice, one progress signal, and one supportive check-in.",
    finalQuestion: "What would make this goal feel more owned, doable, and connected?",
  },
  procrastination: {
    focus: "Procrastination is less about laziness than about unnecessary delay used to manage discomfort now at a cost later.",
    everydaySignal: "Notice productive-looking avoidance, endless preparation, task switching, or waiting for the right mood before beginning.",
    quickMisread: "Delay can look like poor time awareness when the immediate function is often mood repair or escape from ambiguity.",
    betterQuestion: "What feeling does postponing relieve, and what smaller action would make starting less aversive?",
    researchAngle: "Research connects procrastination with temporal discounting, task aversion, impulsivity, self-regulation, and emotion repair.",
    boundary: "Not all delay is procrastination; waiting can be strategic when it improves information, timing, or priorities.",
    practiceIntro: "Use it for writing, studying, admin work, health tasks, and decisions that stay vague.",
    fieldTest: "Set a five-minute start that only defines the next visible artifact, not the whole finished product.",
    finalQuestion: "What discomfort is the delay successfully regulating?",
  },
  "habit-formation": {
    focus: "Habit formation is about stable cues making useful actions easier to start with less deliberation.",
    everydaySignal: "Look for behaviors tied to a time, place, preceding action, object, or social routine.",
    quickMisread: "A habit can be mistaken for willpower when the environment is doing much of the initiation work.",
    betterQuestion: "What cue will reliably invite the behavior, and what reward or relief keeps it worth repeating?",
    researchAngle: "Field studies track repeated behavior and automaticity over time to see how context stability and repetition change initiation.",
    boundary: "Habits form at different speeds, remain context-sensitive, and can coexist with conscious goals.",
    practiceIntro: "Use it for exercise, study, sleep, nutrition, creative practice, and recurring maintenance.",
    fieldTest: "Attach one tiny behavior to a cue that already happens daily, then leave the needed object in that cue's path.",
    finalQuestion: "What cue can carry this action when motivation is absent?",
  },
  "affective-forecasting": {
    focus: "Affective forecasting asks why predictions about future feelings often miss intensity, duration, or adaptation.",
    everydaySignal: "Notice certainty that an acceptance, rejection, purchase, move, or embarrassment will dominate emotional life for a long time.",
    quickMisread: "The imagined event can feel like the whole future because the simulation leaves out ordinary context and coping.",
    betterQuestion: "What else will be happening in my life after this event, and how have similar feelings changed before?",
    researchAngle: "Studies compare predicted emotional reactions with later reported experience, often testing focalism and adaptation.",
    boundary: "People often predict emotional direction well; errors are commonly about magnitude and duration.",
    practiceIntro: "Use it for major purchases, applications, breakups, relocations, career choices, and feared social moments.",
    fieldTest: "Before an outcome, predict intensity and duration. Afterward, record when attention returned to other parts of life.",
    finalQuestion: "What is missing from the movie of your future feeling?",
  },
  "hedonic-adaptation": {
    focus: "Hedonic adaptation describes how emotional reactions to changed circumstances often fade as attention and expectations update.",
    everydaySignal: "Watch for upgrades, wins, annoyances, or routines that feel intense at first and then become background.",
    quickMisread: "Fading excitement can be mistaken for choosing wrongly when novelty may simply be wearing off.",
    betterQuestion: "Will this change alter daily experience after it becomes ordinary, or mostly produce a short-lived contrast?",
    researchAngle: "Research follows well-being and attention over time after positive or negative changes to estimate adaptation patterns.",
    boundary: "Adaptation is incomplete for many chronic, uncertain, painful, or socially meaningful conditions.",
    practiceIntro: "Use it for purchases, lifestyle changes, gratitude, workplace perks, and expectations about future happiness.",
    fieldTest: "Before chasing an upgrade, list which daily moments it will still change after the novelty period ends.",
    finalQuestion: "What part of this change will remain after it becomes normal?",
  },
  "self-concept": {
    focus: "Self-concept organizes the stories and categories people use to understand who they are across situations.",
    everydaySignal: "Notice identity phrases such as 'I am bad at this,' 'I am the responsible one,' or 'people like me do not do that.'",
    quickMisread: "A self-description can sound like a fixed essence when it may be a schema shaped by roles, memory, and feedback.",
    betterQuestion: "In which contexts is this self-belief accurate, useful, limiting, or out of date?",
    researchAngle: "Research examines self-schemas, autobiographical memory, roles, culture, and how self-knowledge guides attention and behavior.",
    boundary: "The self is neither infinitely flexible nor permanently fixed; stability and revision coexist.",
    practiceIntro: "Use it for coaching, learning, relationships, career change, and interpreting feedback.",
    fieldTest: "Take one identity sentence and rewrite it as a context-specific pattern with exceptions and evidence.",
    finalQuestion: "Which self-story is guiding attention before experience begins?",
  },
  "social-comparison": {
    focus: "Social comparison explains how other people's outcomes become reference points for judging our own progress, worth, or options.",
    everydaySignal: "Notice mood shifts after salaries, promotions, bodies, lifestyles, grades, or curated posts become comparison targets.",
    quickMisread: "A comparison can feel like objective self-knowledge when the sample is selective and the target's hidden context is missing.",
    betterQuestion: "Why this comparison target, in this domain, at this moment?",
    researchAngle: "Studies examine comparison direction, similarity, attainability, motive, and effects on self-evaluation and behavior.",
    boundary: "Comparisons can inform, inspire, discourage, or distort depending on domain, closeness, and perceived attainability.",
    practiceIntro: "Use it for social media, workplaces, education, fitness, parenting, and financial self-assessment.",
    fieldTest: "When a comparison stings, name the domain, the missing denominator, and one comparison that would be more useful for learning.",
    finalQuestion: "Is this comparison informing you or merely ranking you?",
  },
  "attachment-theory": {
    focus: "Attachment theory concerns expectations about support, safety, and closeness built through repeated relationship experience.",
    everydaySignal: "Look for patterns in seeking reassurance, withdrawing under stress, trusting repair, or expecting rejection.",
    quickMisread: "Attachment language is often turned into fixed personality types when patterns can vary by relationship and change over time.",
    betterQuestion: "What expectation about availability or safety is being activated in this relationship context?",
    researchAngle: "Research uses observations, interviews, questionnaires, and longitudinal designs to connect caregiving histories with later relationship patterns.",
    boundary: "Measurement, culture, development, current partners, and life events all complicate simple type labels.",
    practiceIntro: "Use it in parenting, therapy, close relationships, support seeking, and conflict repair.",
    fieldTest: "During one relationship stress moment, write the support you expected, the cue that triggered it, and what actually happened.",
    finalQuestion: "What does this relationship teach your nervous system to expect?",
  },
  empathy: {
    focus: "Empathy is a family of capacities: sharing feeling, understanding perspective, caring, and regulating your own response.",
    everydaySignal: "Notice the difference between feeling with someone, accurately reading them, and knowing what help they want.",
    quickMisread: "Empathy can be mistaken for automatic kindness or accuracy, though it can be biased, selective, or overwhelming.",
    betterQuestion: "Am I resonating emotionally, taking perspective, checking accuracy, or choosing a helpful response?",
    researchAngle: "Research separates affective resonance, cognitive perspective-taking, empathic concern, accuracy, and fatigue.",
    boundary: "Closeness, similarity, group membership, burnout, and regulation can all shape empathic response.",
    practiceIntro: "Use it in management, caregiving, friendship, conflict, design research, and cross-cultural communication.",
    fieldTest: "Before offering help, reflect what you think the other person feels and ask what you are missing.",
    finalQuestion: "Which kind of empathy does this moment actually need?",
  },
  "mere-exposure-effect": {
    focus: "The mere exposure effect explains why familiarity can warm preference even without new reasons.",
    everydaySignal: "Notice songs, faces, logos, routes, or ideas becoming easier to like after repeated low-pressure encounters.",
    quickMisread: "Liking can be mistaken for objective quality when perceptual fluency and safety signals may be contributing.",
    betterQuestion: "Do I prefer this because it is better, or because it has become easier to process?",
    researchAngle: "Studies vary exposure frequency while controlling stimulus content, then measure liking under different awareness conditions.",
    boundary: "Repetition can produce boredom or irritation, especially when exposure is forced, intense, or attached to dislike.",
    practiceIntro: "Use it for learning, branding, music, design adoption, social familiarity, and idea acceptance.",
    fieldTest: "Before judging a familiar option, compare it with a less familiar alternative after giving both equal attention.",
    finalQuestion: "Is familiarity making this feel true, safe, or good?",
  },
  "spotlight-effect": {
    focus: "The spotlight effect is the tendency to overestimate how much others notice our appearance and behavior.",
    everydaySignal: "Watch for small mistakes, stains, awkward comments, or performance slips feeling publicly magnified.",
    quickMisread: "Your own intense awareness can feel like evidence that everyone else is equally aware.",
    betterQuestion: "What were other people actually trying to do or monitor at that moment?",
    researchAngle: "Experiments compare actors' estimates of being noticed with observers' actual reports.",
    boundary: "Some situations genuinely draw attention; the effect is an average tendency, not a promise of invisibility.",
    practiceIntro: "Use it for presentations, social anxiety, classrooms, interviews, and everyday embarrassment.",
    fieldTest: "After a minor awkward moment, estimate how many people noticed, then ask what each person was likely focused on instead.",
    finalQuestion: "How much of the spotlight is coming from your own attention?",
  },
  "illusion-of-transparency": {
    focus: "The illusion of transparency is about overestimating how clearly private feelings leak into public view.",
    everydaySignal: "Notice nervousness, attraction, frustration, or uncertainty feeling obvious despite limited external cues.",
    quickMisread: "Because an inner state is vivid to you, it can feel equally visible to observers.",
    betterQuestion: "What observable cues would someone actually have, and how ambiguous are those cues?",
    researchAngle: "Studies compare people's estimates of how readable their internal states are with observers' actual accuracy.",
    boundary: "Close relationships, strong expressions, and clear behavior can improve accuracy; people are not completely opaque.",
    practiceIntro: "Use it for public speaking, negotiation, difficult conversations, teaching, and emotional disclosure.",
    fieldTest: "Before assuming your feeling is obvious, name the specific visible cue and one alternative interpretation of it.",
    finalQuestion: "What evidence would an observer have besides your private experience?",
  },
  "barnum-effect": {
    focus: "The Barnum effect explains why broad, flattering, or balanced statements can feel uniquely personal.",
    everydaySignal: "Watch for personality descriptions that mix virtues with mild flaws and could fit almost anyone.",
    quickMisread: "A feeling of recognition can be mistaken for diagnostic accuracy.",
    betterQuestion: "What part of this description would clearly not apply to many people?",
    researchAngle: "Classic demonstrations give people identical vague feedback and measure how personally accurate they judge it to be.",
    boundary: "Specific, validated, independently checked assessment is different from accepting a generic description.",
    practiceIntro: "Use it for personality tests, horoscopes, coaching claims, hiring tools, and feedback conversations.",
    fieldTest: "Underline every phrase in a description that would fit most people you know. Judge only what remains.",
    finalQuestion: "Is this statement personal, or just easy to personalize?",
  },
  "placebo-nocebo": {
    focus: "Placebo and nocebo effects show how expectations, learning, and care context can change symptoms and experience.",
    everydaySignal: "Notice rituals, clinician confidence, warning language, prior treatment memories, or side-effect expectations shaping how sensations are interpreted.",
    quickMisread: "These effects are often dismissed as fake, when expectation and physiology can interact without inventing a miracle cure.",
    betterQuestion: "What expectations and learned associations surround this treatment or symptom?",
    researchAngle: "Research uses control conditions, expectation manipulation, conditioning, and symptom measures to separate context effects from active treatment effects.",
    boundary: "Placebo effects do not justify deception or replacing effective care, and they do not explain every improvement.",
    practiceIntro: "Use it for health communication, pain, side-effect counseling, treatment routines, and interpreting symptom changes.",
    fieldTest: "When discussing a treatment, pair honest uncertainty with supportive context and balanced framing of benefits and risks.",
    finalQuestion: "What is the care context teaching the body to expect?",
  },
  "peak-end-rule": {
    focus: "The peak-end rule highlights how memory for an episode can lean heavily on its most intense moment and its ending.",
    everydaySignal: "Watch trips, meetings, medical procedures, dates, or customer experiences being judged by one peak and the final note.",
    quickMisread: "A remembered evaluation can be mistaken for a full average of every moment.",
    betterQuestion: "What were the peak and ending, and do they represent the whole experience?",
    researchAngle: "Studies manipulate episode sequences, peaks, endings, and duration to compare remembered evaluation with moment-by-moment reports.",
    boundary: "Duration and other moments can matter, especially when goals, meaning, or repeated experiences are involved.",
    practiceIntro: "Use it for service design, meetings, events, healthcare, travel, and personal reflection.",
    fieldTest: "End one recurring experience deliberately: recap progress, reduce final friction, or add a clear moment of closure.",
    finalQuestion: "Which moment will this experience ask memory to keep?",
  },
  "correlation-causation": {
    focus: "Correlation and causation is the discipline of asking whether variables move together because one changes the other, or for another reason.",
    everydaySignal: "Watch for headlines where people who do X also have Y, followed by advice that assumes X caused Y.",
    quickMisread: "A clean association can be mistaken for an intervention claim.",
    betterQuestion: "What else could cause both variables, and what comparison would estimate the effect of changing one of them?",
    researchAngle: "Causal inference depends on temporal order, credible comparison groups, mechanisms, randomization when possible, and sensitivity to alternatives.",
    boundary: "Experiments can be narrow or impractical, while strong observational designs can sometimes support causal claims.",
    practiceIntro: "Use it for health claims, education research, product metrics, policy arguments, and personal self-tracking.",
    fieldTest: "For one correlation claim, draw three arrows: X causes Y, Y causes X, and Z causes both.",
    finalQuestion: "What comparison would make this causal claim believable?",
  },
  "effect-size": {
    focus: "Effect size asks how large a difference or relationship is, not merely whether it can be detected statistically.",
    everydaySignal: "Notice claims that emphasize significance, breakthrough, or proven effect without saying how much changed.",
    quickMisread: "A reliable result can be mistaken for a practically important one.",
    betterQuestion: "How large is the effect in meaningful units, and is that magnitude worth the cost, risk, or attention?",
    researchAngle: "Methods work distinguishes standardized differences, correlations, risk ratios, and raw-unit effects because each answers a different magnitude question.",
    boundary: "Small effects can matter at population scale, while large-looking standardized effects can hide poor measurement or narrow samples.",
    practiceIntro: "Use it for reading studies, A/B tests, education interventions, clinical claims, and management metrics.",
    fieldTest: "For one research claim, find the actual difference in natural units before reading the authors' conclusion.",
    finalQuestion: "How much changed, for whom, and at what cost?",
  },
  replication: {
    focus: "Replication asks whether a finding survives new attempts to observe it, either closely or across meaningful variations.",
    everydaySignal: "Notice exciting one-study claims, especially when the setup is flexible, surprising, or far from the application being sold.",
    quickMisread: "One successful study can be treated as settlement, or one failed replication as total disproof.",
    betterQuestion: "Has an independent team found a similar pattern under conditions that matter for the claim?",
    researchAngle: "Replication work separates computational reproducibility, direct replication, robustness checks, and generalization across settings.",
    boundary: "A replication failure may reveal noise, changed conditions, weak theory, or an original false positive; interpretation takes detail.",
    practiceIntro: "Use it for evaluating headlines, interventions, workplace ideas, education claims, and psychological effects with broad public appeal.",
    fieldTest: "Before trusting a striking result, look for independent replications and note whether they tested the same claim or a nearby one.",
    finalQuestion: "What would make this finding survive contact with a new lab, sample, or setting?",
  },
  "publication-bias": {
    focus: "Publication bias is about the visible literature becoming an unrepresentative sample of all the studies that were run.",
    everydaySignal: "Watch for fields where positive, surprising, or clean findings are much easier to find than null or messy ones.",
    quickMisread: "A pile of published support can be mistaken for a pile of all the evidence.",
    betterQuestion: "What studies would have been less likely to appear, and how would their absence change the conclusion?",
    researchAngle: "Meta-research uses funnel plots, registries, p-curve methods, registered reports, and sensitivity analyses to infer missing evidence.",
    boundary: "Bias-detection tools rely on assumptions; they can warn about distortion but cannot perfectly reconstruct the file drawer.",
    practiceIntro: "Use it when reading meta-analyses, intervention claims, supplements, productivity methods, and any literature with strong incentives.",
    fieldTest: "Search for pre-registrations, registered reports, or null results before accepting a clean narrative from published positives.",
    finalQuestion: "What would the evidence look like if the missing studies were visible?",
  },
  "measurement-quality": {
    focus: "Measurement quality asks whether the numbers or observations actually support the interpretation being placed on them.",
    everydaySignal: "Notice one-item scores, vague labels, noisy proxies, inconsistent ratings, or metrics treated as the construct itself.",
    quickMisread: "A precise-looking number can be mistaken for a valid measurement.",
    betterQuestion: "Reliable for what, valid for which interpretation, in which population, and for what decision?",
    researchAngle: "Measurement work examines reliability, validity evidence, construct definition, scoring, invariance, and error.",
    boundary: "Validity belongs to a use and interpretation, not to a test forever in every context.",
    practiceIntro: "Use it for surveys, dashboards, psychological scales, hiring rubrics, grades, and health screeners.",
    fieldTest: "For one metric, write the construct you care about and three ways the metric could miss or distort it.",
    finalQuestion: "What exactly does this measure earn the right to mean?",
  },
};

export function getArticleSpecifics(article: Article): ArticleSpecifics {
  const angle = angles[article.slug] ?? {
    focus: `${article.title} is most useful when it points to the conditions that make the pattern more or less likely.`,
    everydaySignal: article.example,
    quickMisread: "The surface behavior can be mistaken for a complete explanation.",
    betterQuestion: "What changed in the situation, evidence, cue, or comparison that could make this pattern more likely?",
    researchAngle: article.mechanism,
    boundary: article.limitation,
    practiceIntro: "Use the concept when it helps improve a concrete process rather than label a person.",
    fieldTest: "Watch for one real example this week and write the cue, interpretation, alternative explanation, and outcome.",
    finalQuestion: `Where would noticing ${article.title.toLowerCase()} change the next question you ask?`,
  };

  return {
    ...angle,
    process: [
      { title: "A cue sets the stage", detail: angle.everydaySignal },
      { title: "The cue changes what carries weight", detail: article.mechanism },
      { title: "The boundary decides how far it travels", detail: angle.boundary },
    ],
    myths: [
      { myth: "The surface behavior tells the whole story.", reality: angle.quickMisread },
      { myth: "One example proves the concept is present.", reality: angle.betterQuestion },
      { myth: "The same fix works everywhere.", reality: angle.boundary },
    ],
  };
}
